### Variables 
@apiurl = http://localhost:8000
@apiendpoint = task-lists

### POST - create list_task
POST {{apiurl}}/{{apiendpoint}} HTTP/1.1
Content-Type: application/json

{
   "title": "Home list"
}

### GET - list task lists
GET {{apiurl}}/{{apiendpoint}} HTTP/1.1